port: 9047
kubectl_dir: "/usr/bin/"
guard_token: "xxx"
upgrade_base_dir: /root/nas/workspaces/deployment
end_msg: "Task successfully end"
log:
  appenders:
    dateFile:
      filename: logs/deploy
      daysToKeep: 10
      pattern: yyyy-MM-dd.log
  categories:
    default:
      appenders:
        - dateFile
        - console
      level: debug
